server:
  port: 8800

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: nginx-service
          uri: http://google.com
          predicates:
            - Path=/nginx/**
          filters:
            - RewritePath=/nginx/?(?<path>.*),/$\{path}
        - id: httpd-service
          uri: http://daum.net
          predicates:
            - Path=/httpd/**
          filters:
            - RewritePath=/httpd/?(?<segment>.*), /$\{segment}


logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug
    com.kt: trace
